version: '3'
services:
  web:
    image: dhis2/dhis2-web:trunk-tomcat7-jre8-latest
    container_name: dhis2
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./includes/dhis.conf:/opt/dhis2/config/dhis.conf
      - ./includes/server.xml:/usr/local/tomcat/conf/server.xml
    depends_on:
      - "db"
  db:
    image: mdillon/postgis
    container_name: postgres
    command: "postgres -c max_locks_per_transaction=100"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./datadb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dhis2
      POSTGRES_USER: dhis
      POSTGRES_PASSWORD: dhis
  proxy:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./includes/nginx_default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - "web"
